[env]
TERM = "xterm-256color"

[window]
decorations = "none"
dynamic_title = false
startup_mode = "Maximized"
title = "Alacritty"

[font]
size = 14
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font Mono", style = "Bold Italic" }

[colors]
primary = { background = "#282c34", foreground = "#abb2bf" }
selection = { background = "#3e4451", text = "CellForeground" }

[colors.normal]
black = "#5c6370"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#828997"

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullScreen" },
]
