[colors.normal]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#828997"
yellow = "#e5c07b"

[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[colors.selection]
background = "#3e4451"
text = "CellForeground"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[keyboard]
bindings = [
  { key = "N", mods = "Command", action = "ReceiveChar" },
  { key = "W", mods = "Command", action = "ReceiveChar" },
  { key = "T", mods = "Command", action = "ReceiveChar" },
  { key = "F10", action = "ToggleFullScreen" },
]

[window]
startup_mode = "Maximized"
dynamic_title = false
decorations = "none"
title = "Alacritty"


[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
